### ISSUE TITLE
Discussion: About Post Middleware that needs: Result from Service, http.Request, ResponseWriter

### ISSUE THREAD

**Issue by sunfmin** [theplant/prottp#10]
Right now the middleware wrapped around `prottp.Service` can only do logic with http.Request, But is not possible to do writing to ResponseWriter that depends on the result of `prottp.Service`.

Take `Login` for example, We have a `prottp.Service` that do the real login, and return auth_code, But it's difficult to write that value into Cookie.

The current solution that @tnclong made, passing http.Request/ResponseWriter inside Context, is quite ugly I think, request.Context() has a request, and response writer... :trollface: 

It would be nice if we can solve this kind of middleware at prottp library.

One of my suggestions is the pull request https://github.com/theplant/prottp/pull/4, Instead of converting the `prottp.Service` into an `http.Handler`, which can only be put into the most inner in the stack of the middleware, which defeats the possibility of writing things to response writer.  We can also convert it into `server.Middleware`, then you can stack more middleware after it, like: `	prottp.Handle(mux, fetchValueFromContextAndWriteCookie, prottp.Middleware(a), mustLogin)
`

**Comment by bodhi** [comment]
Quick overview for sake of discussion. Prottp provides these features:

1. Standardised mapping of Protocol Buffer `rpc` definition to URL path
2. Generate `http.HandlerFunc` for an RPC service *method* definition + service interface implementation
3. Decode PB message from `*http.Request`
4. Write PB message to `http.ResponseWriter`
5. Simple factory to use 1-4 to make an `rpc` interface implementation accessible over HTTP in a standard way.

---

> We can also convert it into `server.Middleware`, then you can stack more middleware after it

The problem with this is that it's hard to understand how a service is "middleware". Services are just functions: input -> output.

For example: When does it execute the next handler?

1. Before decoding the request's `proto.Message`.
2. Before executing the service handler.
3. Before writing the handler's `proto.Message` response.
4. After writing the response.

In this particular case, you would want to execute at 3. But as generic middleware, there's no particular reason to decide on 3 instead of one of the other points.


---

I can see several other approaches:

1. Use request side of prottp directly
2. Write middleware that makes `http.ResponseWriter.Headers()` accessible via `r.Context()`
3. Adapt prottp to accept an "interceptor" in the same way that grpc does

# 1. Use request side of prottp directly

Extract the request decoding part out of prottp:

```go
func Decode(r *http.Request, out proto.Message) error {
	isJson := strings.Index(r.Header.Get("Content-Type"), "application/json") >= 0

	if isJson {
		return unmarshaler.Unmarshal(r.Body, out)
	}

	var buff []byte
	buff, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return err
	}
	return proto.Unmarshal(buff, out)
}
```

Then you can just write a custom handler that uses `prottp.Decode`:

```
func custom(w http.ResponseWriter, r *http.Request) {
	var msg SearchRequest

	if err := prottp.Decode(r, &msg); err != nil {
		panic(err)
	}

	service := search{}

	result, err := service.Search(r.Context(), &msg)
	if err != nil {
		panic(err)
	}

	h := w.Header()

	h.Set("X-Custom-Header", fmt.Sprintf("%v", result))
	h.Set("X-SnakeName", fmt.Sprintf("%d", result.Result[0].SomeSnakedName))

	w.WriteHeader(http.StatusNoContent)
}
```

Pros: it's simple and direct.

Cons:

* Since it's not an `rpc` interface, implementation is not consistent with other services (feature 5
* you can't use feature 1, so the service path is not standardised.
* Because of above, we lose automatic client-side usage via tooling.

# 2. Middleware for Context access to headers

Make response headers available via request context:

```go
func WithHeader(http.Handler) http.Handler { ... }

func Header(context.Context) (http.Header, bool) { ... }
// Header, but panics if header not in context
func ForceHeader(context.Context) (http.Header, bool) { ... }
```

Then use these inside the service implementation:

```go
type search struct{}

func (s service) Search(ctx context.Context, *InputMsg) (*OutputMsg, error) {
	// ...
	h := ForceHeader(ctx)
	h.Set("Set-Cookie", SomeCookie)
	// ...
}
```

Pros: requires no change to prottp

Cons: 

* Behaviour is not obvious from `rpc` definition
* Couples service to presence of header middleware
* Client needs to be aware of special behaviour

# 3. Adapt prottp to accept an "interceptor"

This is a way to "embed" custom "back-end" (request writing) behaviour inside of a prottp service. Adjust the interface of `prottp.Handle` to accept something like `func(proto.Message, http.ResponseWriter)`.

Then, instead of writing out the `proto.Message` to the `http.ResponseWriter`, prottp calls the interceptor, and the interceptor can do things like set cookies, or...?

This is quite similar to your middleware idea.

---

Out of the 3 options, for this use case (setting a cookie) I think 2 is the best approach. It solves the immediate problem with no changes to prottp. It's not quite as flexible as the other two, but I don't think the flexibility is actually useful.

**Comment by sunfmin** [comment]
I'll create a pull request for Option 2.

**Comment by sunfmin** [comment]
The bad thing about Option 2 is that We can't use qor/auth's SessionStorerInterface anymore: the current implementation in Mastani: https://github.com/theplant/mastani/blob/add-users/auth/auth.go#L73, Since it takes a Request and ResponseWriter...

**Comment by bodhi** [comment]
> The bad thing about Option 2 is that We can't use qor/auth's SessionStorerInterface anymore

You can't use it *directly*, but you can wrap it inside the middleware, and expose the features you need.

Or talk to @jinzhu about how to make `qor.Auth` and `qor.Session` more friendly to `prottp`-style functions that don't have access to the request and response.

**Comment by sunfmin** [comment]
https://github.com/theplant/prottp/pull/11
